export const ActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_CANCELLED: 'LOGIN_CANCELLED',
  SAVE_TOKEN: 'SAVE_TOKEN',
  DELETE_TOKEN: 'DELETE_TOKEN',

  FETCH_EMPLOYEES_PENDING: 'FETCH_EMPLOYEES_PENDING',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
  FETCH_EMPLOYEES_FAILURE: 'FETCH_EMPLOYEES_FAILURE',
  FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',

  DELETE_EMPLOYEE_PENDING: 'DELETE_EMPLOYEE_PENDING',
  DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
  DELETE_EMPLOYEE_FAILURE: 'DELETE_EMPLOYEE_FAILURE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',

  ADD_EMPLOYEES_PENDING: 'ADD_EMPLOYEES_PENDING',
  ADD_EMPLOYEES_SUCCESS: 'ADD_EMPLOYEES_SUCCESS',
  ADD_EMPLOYEES_FAILURE: 'ADD_EMPLOYEES_FAILURE',
  ADD_EMPLOYEES: 'ADD_EMPLOYEES',

  SAVE_EMPLOYEE_PENDING: 'SAVE_EMPLOYEE_PENDING',
  SAVE_EMPLOYEE_SUCCESS: 'SAVE_EMPLOYEE_SUCCESS',
  SAVE_EMPLOYEE_FAILURE: 'SAVE_EMPLOYEE_FAILURE',
  SAVE_EMPLOYEE: 'SAVE_EMPLOYEE',

  FETCH_EMPLOYEE_PENDING: 'FETCH_EMPLOYEE_PENDING',
  FETCH_EMPLOYEE_SUCCESS: 'FETCH_EMPLOYEE_SUCCESS',
  FETCH_EMPLOYEE_FAILURE: 'FETCH_EMPLOYEE_FAILURE',
  FETCH_EMPLOYEE: 'FETCH_EMPLOYEE',
};
